package com.eventor;

import java.util.Map;
import com.eventor.model.entity.Event;
import com.eventor.model.repository.EventRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;


/**
 * A class for getting the newEvent.html and create new Event account
 */
@Controller
public class NewEventController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private EventRepository eventRepository;

    /**
     * Function for displaying .html content.
     * @return String containing the name of .html file to display.
     */
    @RequestMapping("/newEvent")
    public String newEvent(Map<String, Object> model) {
        Event event = new Event();
        model.put("event", event);
        return "newEvent";
    }

    @RequestMapping(value = "/processFormEvent", method= RequestMethod.POST)
    public String processForm(@ModelAttribute(value="event") Event event, Map<String, Object> model) {
        eventRepository.save(event);

        model.put("type", "event");
        model.put("success", 1);
        return "result"; //shoud be success = 1
    }

}