package com.eventor;

import java.sql.Connection;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.DriverManager;

import java.util.Map;
import com.eventor.model.entity.User;
import com.eventor.model.repository.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;


/**
 * A class for getting the index.html and manage SQL database connection.
 */
@Controller
public class NewUserController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    /**
     * Function for displaying .html content.
     * @return String containing the name of .html file to display.
     */
    @RequestMapping("/newUser")
    public String newUser(Map<String, Object> model) {
        User user = new User();
        model.put("user", user);
        return "newUser";
    }

    @RequestMapping(value = "/processForm", method= RequestMethod.POST)
    public String processForm(@ModelAttribute(value="user") User user) {
        userRepository.save(user);
        return "index?success=1";
    }


}